title: Data Science Projects
author: Eugene Olkhov
email: eugeneolkhov@gmail.com

# social links

github_username:  @eugeneolkhov

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
